# Generated by Django 5.1.15 on 2026-10-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('rule_mode', models.CharField(choices=[('inform', 'Информирует (изменения разрешены, сотрудник уведомляется)'), ('restrict', 'Ограничивает (вне окна блокируется оформление и отмена)')], default='inform', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('target_segments', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Окно выбора (Кампания)',
                'verbose_name_plural': 'Окна выбора (Кампании)',
                'ordering': ['-start_date'],
            },
        ),
    ]
