# Generated by Django 5.1.15 on 2026-10-01 09:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DMSProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('insurer', models.CharField(default='Ингосстрах', max_length=100)),
                ('description', models.TextField()),
                ('price_points', models.PositiveIntegerField(default=3000)),
                ('is_default', models.BooleanField(default=False)),
                ('includes', models.JSONField(blank=True, default=list)),
                ('excludes', models.JSONField(blank=True, default=list)),
                ('clinics', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Программа ДМС',
                'verbose_name_plural': 'Программы ДМС',
            },
        ),
        migrations.CreateModel(
            name='DMSChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('upgrade', 'Расширение программы'), ('switch_program', 'Замена базовой программы'), ('opt_out', 'Отказ от базового ДМС')], max_length=30)),
                ('selected_options', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('submitted', 'Заявка отправлена'), ('approved', 'Одобрено'), ('completed', 'Исполнено'), ('rejected', 'Отклонено')], default='submitted', max_length=30)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dms_requests', to=settings.AUTH_USER_MODEL)),
                ('target_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='health_dms.dmsprogram')),
            ],
            options={
                'verbose_name': 'Заявка на изменение ДМС',
                'verbose_name_plural': 'Заявки на изменение ДМС',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDMSPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('pending_upgrade', 'На согласовании замены'), ('opted_out', 'Отказ от базового ДМС'), ('expired', 'Истёк')], default='active', max_length=30)),
                ('valid_until', models.DateField(default=django.utils.timezone.now)),
                ('is_opted_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='health_dms.dmsprogram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dms_policy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Полис сотрудника',
                'verbose_name_plural': 'Полисы сотрудников',
            },
        ),
        migrations.CreateModel(
            name='FamilyMemberDMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10)),
                ('relationship', models.CharField(choices=[('spouse', 'Супруг / супруга'), ('child', 'Ребёнок'), ('parent', 'Родитель')], max_length=20)),
                ('price_points', models.PositiveIntegerField(default=2000)),
                ('status', models.CharField(choices=[('submitted', 'Заявка отправлена'), ('processing', 'В оформлении'), ('active', 'Полис активен'), ('rejected', 'Отклонено')], default='submitted', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_dms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ДМС члена семьи',
                'verbose_name_plural': 'ДМС членов семьи',
            },
        ),
    ]
