# Generated by Django 5.1.15 on 2026-10-01 09:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.IntegerField(default=0)),
                ('frozen_balance', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Балльный счет',
                'verbose_name_plural': 'Балльные счета',
            },
        ),
        migrations.CreateModel(
            name='PointLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_type', models.CharField(choices=[('burnable', 'Сгораемые'), ('non_burnable', 'Несгораемые')], db_index=True, default='burnable', max_length=20)),
                ('initial_amount', models.PositiveIntegerField()),
                ('current_balance', models.PositiveIntegerField()),
                ('accrued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Партия баллов (Lot)',
                'verbose_name_plural': 'Партии баллов',
                'ordering': ['expires_at', 'accrued_at'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('accrual', 'Начисление'), ('spend', 'Списание'), ('expire', 'Сгорание'), ('refund', 'Возврат'), ('manual_add', 'Ручное начисление'), ('manual_sub', 'Ручное списание'), ('freeze', 'Заморозка'), ('unfreeze', 'Разморозка'), ('transfer_in', 'Входящий перевод'), ('transfer_out', 'Исходящий перевод'), ('donation', 'Благотворительность')], db_index=True, max_length=20)),
                ('amount', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='points.pointaccount')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Транзакция баллов',
                'verbose_name_plural': 'Журнал транзакций баллов',
                'ordering': ['-created_at'],
            },
        ),
    ]
