# Generated by Django 5.1.15 on 2026-10-01 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rule_type', models.CharField(choices=[('daily_spend_limit', 'Превышение суточного списания'), ('frequent_transfers', 'Частые переводы между сотрудниками'), ('abnormal_accrual', 'Аномально крупное начисление'), ('multiple_failed_totp', 'Множественные ошибки 2FA')], max_length=50)),
                ('threshold', models.FloatField(default=10000.0)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], default='medium', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('detected', 'Обнаружено'), ('legitimate', 'Легитимно'), ('blocked', 'Аккаунт заблокирован')], default='detected', max_length=20)),
                ('resolution_comment', models.TextField(blank=True, default='')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_anomalies', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='audit.anomalyrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('accrual', 'Начисление баллов'), ('deduction', 'Списание баллов'), ('refund', 'Возврат баллов'), ('transfer', 'Перевод баллов'), ('donation', 'Благотворительность'), ('budget_change', 'Изменение бюджета'), ('role_change', 'Смена роли пользователя'), ('permission_change', 'Изменение матрицы прав'), ('setting_change', 'Изменение настройки платформы'), ('account_freeze', 'Заморозка счета'), ('account_unfreeze', 'Разморозка счета'), ('anomaly_action', 'Действие по аномалии'), ('order_action', 'Действие с заказом'), ('login_2fa', 'Подтверждение 2FA')], db_index=True, max_length=50)),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, default='', max_length=50)),
                ('integrity_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at'],
            },
        ),
    ]
