# Generated by Django 5.1.15 on 2026-10-01 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, default='ShoppingBag', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('allowed_segments', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Раздел витрины',
                'verbose_name_plural': 'Разделы витрины',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='Обучение', max_length=100)),
                ('supplier', models.CharField(default='Кафетерий льгот', max_length=150)),
                ('price', models.PositiveIntegerField(default=1000)),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('tag', models.CharField(blank=True, default='', max_length=50)),
                ('product_type', models.CharField(choices=[('physical', 'Физический товар'), ('digital', 'Цифровой товар / сертификат'), ('virtual_card', 'Виртуальная банковская карта'), ('doc_benefit', 'Льгота с подтверждающими документами'), ('gift_service', 'Подарочный сервис (Giftery/ПВК)'), ('booked_service', 'Услуга по записи'), ('accommodation', 'Проживание / база отдыха'), ('education', 'Обучение и сертификация'), ('vacation_days', 'Дополнительный день отпуска'), ('flexible_schedule', 'Гибкий график (нефинансовая льгота)')], default='digital', max_length=30)),
                ('description', models.TextField()),
                ('terms', models.TextField(blank=True, default='')),
                ('pdf_attachment', models.FileField(blank=True, null=True, upload_to='catalog_pdfs/')),
                ('is_general_offer', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approver_type', models.CharField(choices=[('none', 'Не требуется'), ('manager', 'Руководитель'), ('hr', 'HR'), ('both', 'Руководитель и HR')], default='none', max_length=20)),
                ('available_seats', models.IntegerField(blank=True, null=True)),
                ('min_booking_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Позиция каталога',
                'verbose_name_plural': 'Позиции каталога',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='catalog.catalogsection')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
