# Generated by Django 5.1.15 on 2026-10-01 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('criteria_grade', models.CharField(blank=True, default='', max_length=100)),
                ('criteria_department', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сегмент сотрудников',
                'verbose_name_plural': 'Сегменты сотрудников',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=20)),
                ('permission_key', models.CharField(db_index=True, max_length=100)),
                ('is_allowed', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Право роли',
                'verbose_name_plural': 'Матрица прав ролей',
                'unique_together': {('role', 'permission_key')},
            },
        ),
        migrations.CreateModel(
            name='SegmentVisibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('is_visible', models.BooleanField(default=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibility_rules', to='rbac.segment')),
            ],
            options={
                'verbose_name': 'Правило видимости сегмента',
                'verbose_name_plural': 'Правила видимости сегментов',
                'unique_together': {('segment', 'section_name')},
            },
        ),
    ]
