# Generated by Django 5.1.15 on 2026-10-01 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('grade', models.CharField(blank=True, default='', max_length=50)),
                ('department', models.CharField(blank=True, default='', max_length=150)),
                ('segment', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.PositiveIntegerField(default=5000)),
                ('period', models.CharField(choices=[('annual', 'Годовой'), ('monthly', 'Ежемесячный')], default='annual', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('max_sum_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('max_count_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PositionLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_identifier', models.CharField(db_index=True, max_length=100, unique=True)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('max_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('max_per_week', models.PositiveIntegerField(blank=True, null=True)),
                ('max_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('max_lifetime', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.IntegerField(default=2025)),
                ('allocated_amount', models.PositiveIntegerField(default=0)),
                ('spent_amount', models.PositiveIntegerField(default=0)),
                ('is_frozen', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_budgets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_year'],
                'unique_together': {('user', 'period_year')},
            },
        ),
    ]
