# Generated by Django 5.1.15 on 2026-10-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('channel_type', models.CharField(choices=[('1c_zup', '1С:ЗУП'), ('sso', 'Корпоративный SSO'), ('smtp', 'Почтовый шлюз SMTP'), ('giftery', 'Giftery API'), ('prostodar', 'ПВК / Prostodar API'), ('accounting', 'Канал выгрузки в бухгалтерию')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_mock', models.BooleanField(default=True)),
                ('endpoint_url', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('available', 'Доступно'), ('degraded', 'Сбои'), ('unavailable', 'Недоступно')], default='available', max_length=20)),
                ('last_check_at', models.DateTimeField(auto_now=True)),
                ('response_time_ms', models.PositiveIntegerField(default=45)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
        ),
    ]
