import { useRef, useState, type ButtonHTMLAttributes, type ReactNode } from "react";
import { ArrowDown, ArrowRight, Check, ChevronDown, ChevronLeft, ChevronRight, CircleAlert, Coins, FileText, Inbox, LoaderCircle, Search, UploadCloud, X } from "lucide-react";

export const points = (value: number) => `${value.toLocaleString("ru-RU")} б.`;

export function Button({ variant = "primary", loading = false, children, className = "", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "ghost" | "danger"; loading?: boolean }) {
  return <button className={`btn btn-${variant} ${className}`} disabled={loading || props.disabled} {...props}>{loading && <LoaderCircle size={16} className="spin" />}{children}</button>;
}
export function IconButton({ children, label, className = "", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { label: string }) {
  return <button aria-label={label} title={label} className={`icon-btn ${className}`} {...props}>{children}</button>;
}
export function Field({ label, value, onChange, placeholder, type = "text", hint, className = "" }: { label?: string; value?: string; onChange?: (value: string) => void; placeholder?: string; type?: string; hint?: string; className?: string }) {
  return <label className={`field ${className}`}>{label && <span className="field-label">{label}</span>}<input type={type} value={value} onChange={e => onChange?.(e.target.value)} placeholder={placeholder} />{hint && <small>{hint}</small>}</label>;
}
export function Select({ label, value, onChange, options, className = "" }: { label?: string; value: string; onChange: (value: string) => void; options: string[]; className?: string }) {
  return <label className={`field ${className}`}>{label && <span className="field-label">{label}</span>}<span className="select-wrap"><select value={value} onChange={e => onChange(e.target.value)}>{options.map(o => <option key={o}>{o}</option>)}</select><ChevronDown size={16} /></span></label>;
}
export function Toggle({ checked, onChange, label }: { checked: boolean; onChange: (value: boolean) => void; label?: string }) {
  return <label className="toggle-row"><input type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} /><span className="toggle-track" />{label && <span>{label}</span>}</label>;
}
export function Checkbox({ checked, onChange, label }: { checked: boolean; onChange: (value: boolean) => void; label: string }) {
  return <label className="check-row"><input type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} /><span className="check-box"><Check size={12} /></span>{label}</label>;
}
export function Slider({ value, max, onChange }: { value: number; max: number; onChange: (value: number) => void }) { return <input className="slider" type="range" min="0" max={max} value={value} onChange={e => onChange(Number(e.target.value))} />; }
export function DateField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <Field label={label} type="date" value={value} onChange={onChange} />; }
export function Badge({ children, tone = "neutral" }: { children: ReactNode; tone?: "neutral" | "success" | "warning" | "danger" | "info" }) { return <span className={`badge badge-${tone}`}>{children}</span>; }
export function BalancePill({ available, total, onClick }: { available: number; total: number; onClick?: () => void }) { return <button className="balance-pill" onClick={onClick}><span className="coin"><Coins size={17} /></span><span><strong>{points(available)}</strong><small>из {points(total)} доступно</small></span><ChevronDown size={15} /></button>; }
export function Stepper({ steps, active }: { steps: string[]; active: number }) { return <div className="stepper">{steps.map((step, i) => <div className={`step ${i === active ? "active" : ""} ${i < active ? "done" : ""}`} key={step}><span>{i < active ? <Check size={14} /> : i + 1}</span><small>{step}</small></div>)}</div>; }
export function Tabs({ items, value, onChange }: { items: string[]; value: string; onChange: (value: string) => void }) { return <div className="tabs">{items.map(item => <button key={item} className={value === item ? "selected" : ""} onClick={() => onChange(item)}>{item}</button>)}</div>; }
export function Breadcrumbs({ items, onClick }: { items: string[]; onClick?: (index: number) => void }) { return <div className="breadcrumbs">{items.map((item, i) => <span key={`${item}-${i}`} onClick={() => onClick?.(i)}>{item}{i < items.length - 1 && <ChevronRight size={14} />}</span>)}</div>; }
export function Avatar({ name = "АМ", size = "normal" }: { name?: string; size?: "normal" | "small" }) { return <span className={`avatar avatar-${size}`}>{name}</span>; }
export function Progress({ value, max = 100, color = "teal" }: { value: number; max?: number; color?: "teal" | "coral" }) { return <div className="progress"><span className={`progress-${color}`} style={{ width: `${Math.min(100, value / max * 100)}%` }} /></div>; }
export function Alert({ children, tone = "warning", title }: { children: ReactNode; tone?: "warning" | "danger" | "info" | "success"; title?: string }) { return <div className={`alert alert-${tone}`}><CircleAlert size={18} /><div>{title && <strong>{title}</strong>}<span>{children}</span></div></div>; }
export function Modal({ title, children, onClose, footer }: { title: string; children: ReactNode; onClose: () => void; footer?: ReactNode }) { return <div className="overlay" onMouseDown={onClose}><div className="modal" onMouseDown={e => e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><IconButton label="Закрыть" onClick={onClose}><X size={20} /></IconButton></div><div className="modal-body">{children}</div>{footer && <div className="modal-footer">{footer}</div>}</div></div>; }
export function Drawer({ title, children, onClose, footer }: { title: string; children: ReactNode; onClose: () => void; footer?: ReactNode }) { return <div className="overlay" onMouseDown={onClose}><aside className="drawer" onMouseDown={e => e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><IconButton label="Закрыть" onClick={onClose}><X size={20} /></IconButton></div><div className="drawer-body">{children}</div>{footer && <div className="modal-footer">{footer}</div>}</aside></div>; }
export function Toast({ text, onClose }: { text: string; onClose: () => void }) { return <div className="toast"><span className="toast-check"><Check size={15} /></span>{text}<IconButton label="Закрыть" onClick={onClose}><X size={16} /></IconButton></div>; }
export function EmptyState({ title, text, action, onAction }: { title: string; text: string; action?: string; onAction?: () => void }) { return <div className="empty-state"><div className="empty-illustration"><Inbox size={37} strokeWidth={1.4} /></div><h3>{title}</h3><p>{text}</p>{action && <Button variant="secondary" onClick={onAction}>{action}</Button>}</div>; }
export function Skeleton({ rows = 3 }: { rows?: number }) { return <div className="skeleton-list">{Array.from({ length: rows }).map((_, i) => <div className="skeleton-row" key={i}><span /><div><i /><i /></div></div>)}</div>; }
export function FileUploader({ label = "Загрузить файлы" }: { label?: string }) { const ref = useRef<HTMLInputElement>(null); const [files, setFiles] = useState<string[]>([]); return <div><button className="upload" onClick={() => ref.current?.click()}><UploadCloud size={22} /><strong>{label}</strong><small>PDF, JPG или PNG до 10 МБ</small></button><input ref={ref} type="file" multiple hidden onChange={e => setFiles(Array.from(e.target.files ?? []).map(f => f.name))} />{files.map(file => <div className="file-item" key={file}><FileText size={16} />{file}<Check size={15} /></div>)}</div>; }
export type Column<T> = { key: keyof T; label: string; render?: (row: T) => ReactNode };
export function DataTable<T extends { id: string }>({ rows, columns, onRow }: { rows: T[]; columns: Column<T>[]; onRow?: (row: T) => void }) { const [sort, setSort] = useState<keyof T | null>(null); const [asc, setAsc] = useState(true); const [page, setPage] = useState(0); const sorted = [...rows].sort((a, b) => sort ? String(a[sort]).localeCompare(String(b[sort]), "ru") * (asc ? 1 : -1) : 0); return <><div className="table-scroll"><table className="data-table"><thead><tr>{columns.map(c => <th key={String(c.key)} onClick={() => { setAsc(sort === c.key ? !asc : true); setSort(c.key); }}>{c.label} <ArrowDown size={13} /></th>)}</tr></thead><tbody>{sorted.slice(page * 6, page * 6 + 6).map(row => <tr key={row.id} onClick={() => onRow?.(row)}>{columns.map(c => <td key={String(c.key)}>{c.render ? c.render(row) : String(row[c.key])}</td>)}</tr>)}</tbody></table></div><div className="table-footer"><span>Показано {Math.min(rows.length, page * 6 + 1)}–{Math.min(rows.length, (page + 1) * 6)} из {rows.length}</span><div><IconButton label="Назад" disabled={page === 0} onClick={() => setPage(page - 1)}><ChevronLeft size={17} /></IconButton><span>{page + 1}</span><IconButton label="Вперёд" disabled={(page + 1) * 6 >= rows.length} onClick={() => setPage(page + 1)}><ChevronRight size={17} /></IconButton></div></div></>; }
export function SearchField({ value, onChange, placeholder = "Поиск по каталогу" }: { value: string; onChange: (value: string) => void; placeholder?: string }) { return <div className="search-field"><Search size={18} /><input value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} /></div>; }
export function LinkButton({ children, onClick }: { children: ReactNode; onClick: () => void }) { return <button className="link-btn" onClick={onClick}>{children}<ArrowRight size={16} /></button>; }
